/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "buttons": {
        "reg": string;
        "back": string;
        "change_language": string;
    };
    "phrases": {
        "home": string;
        "no-reg-home": string;
        "reg": {
            "welcome": string;
            "age": string;
        };
        "check_pm": string;
        "set-normal-age": string;
        "instructions": string;
        "select_language": string;
    };
    "commands": {
        "start": string;
        "reg": string;
        "instructions": string;
    };
    "languages": {
        "en": string;
        "ru": string;
    };
    "scenes": {
        "reg": {
            "welcome": string;
            "age": string;
        };
        "change_language": string;
        "home": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
